package pvz.models.entities.plants.enums;

public enum PlantType {
    Sunflower,
    TwinSunflower,
    Sunshroom,
    PrimalSunflower,
    GoldBloom,
    Peashooter,
    Repeater,
    Threepeater,
    SnowPea,
    Rotobaga,
    PeaPod,
    SplitPea,
    Citron,
    Caulipower,
    ElectricBlueberry,
    BowlingBulb,
    Cactus,
    FirePeashooter,
    Starfruit,
    GooPeashooter,
    MegaGatlingPea,
    Seashroom,
    Puffshroom,
    Fumeshroom,
    Cabbagepult,
    Kernelpult,
    Melonpult,
    WinterMelon,
    Pepperpult,
    PotatoMine,
    PrimalPotatoMine,
    CherryBomb,
    Squash,
    Grapeshot,
    Jalapeno,
    Doomshroom,
    TangleKelp,
    IcebergLettuce,
    BonkChoy,
    PhatBeet,
    Chomper,
    WasabiWhip,
    Kiwibeast,
    Wallnut,
    Tallnut,
    Endurian,
    Garlic,
    SweetPotato,
    Explodeonut,
    Pumpkin,
    SunBean,
    Torchwood,
    Magnetshroom,
    Hypnoshroom,
    Cattail,
    Imitater,
    Iceshroom,
    LilyPad,
    HotPotato,
    GraveBuster,
    Enlightenmint,
    Appeasemint,
    Armamint,
    Bombardmint,
    Enforcemint,
    Reinforcemint,
    Enchantmint,
    Piercemint,
    catTailmint;

    public static PlantType getTypeByName(String type){
        for (PlantType p: PlantType.values()){
            if (p.toString().equalsIgnoreCase(type)) return p;
        }
        return null;
    }
}
