/*
 * This source file was generated by the Gradle 'init' task
 */
package pvz;

import pvz.View.MenuManager;
import pvz.View.RegisterMenu;

public class App {
    public static void main(String[] args) {
        MenuManager menuManager = new MenuManager();
        menuManager.setCurrentMenu(new RegisterMenu());
        menuManager.handleInput(null);
    }
}
